//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 10:48:05 AM EAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.jee.mcnz.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mcnz.jee.soap;
